/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InstrumentToken = IDL.Record({
  'token' : IDL.Text,
  'exchange' : IDL.Text,
});
export const Session = IDL.Record({
  'consumerSecret' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'consumerKey' : IDL.Text,
  'sessionToken' : IDL.Opt(IDL.Text),
  'accessToken' : IDL.Opt(IDL.Text),
});
export const SymbolInfo = IDL.Record({
  'token' : IDL.Text,
  'instrumentName' : IDL.Text,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text], [IDL.Text], []),
  'clearSession' : IDL.Func([], [], []),
  'completeLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Text], []),
  'getMarketDepth' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getOrders' : IDL.Func([], [IDL.Text], []),
  'getPositions' : IDL.Func([], [IDL.Text], []),
  'getQuotes' : IDL.Func([IDL.Vec(InstrumentToken)], [IDL.Text], []),
  'getSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(SymbolInfo)], ['query']),
  'initiateLogin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InstrumentToken = IDL.Record({
    'token' : IDL.Text,
    'exchange' : IDL.Text,
  });
  const Session = IDL.Record({
    'consumerSecret' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'consumerKey' : IDL.Text,
    'sessionToken' : IDL.Opt(IDL.Text),
    'accessToken' : IDL.Opt(IDL.Text),
  });
  const SymbolInfo = IDL.Record({
    'token' : IDL.Text,
    'instrumentName' : IDL.Text,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text], [IDL.Text], []),
    'clearSession' : IDL.Func([], [], []),
    'completeLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Text], []),
    'getMarketDepth' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getOrders' : IDL.Func([], [IDL.Text], []),
    'getPositions' : IDL.Func([], [IDL.Text], []),
    'getQuotes' : IDL.Func([IDL.Vec(InstrumentToken)], [IDL.Text], []),
    'getSession' : IDL.Func([], [IDL.Opt(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(SymbolInfo)], ['query']),
    'initiateLogin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };